/**
 * Regenerate the table of contents in README.md from its headings,
 * so it can't drift from the actual structure.
 * Run automatically at the end of `.github/workflows/build.sh`,
 * right after generate-tables.js.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const readmePath = path.join(root, 'README.md');

// same slug rules github uses: strip punctuation, spaces to hyphens,
// duplicates get a -1, -2, ... suffix
const slugCounts = {};
const slugify = heading => {
	const base = heading
		.toLowerCase()
		.replace(/<[^>]+>/g, '')
		.replace(/[^\p{L}\p{N} _-]/gu, '')
		.trim()
		.replace(/ /g, '-');
	const count = slugCounts[base] ?? 0;
	slugCounts[base] = count + 1;
	return count === 0 ? base : `${base}-${count}`;
};

const stripInlineMd = heading => heading.replace(/`([^`]*)`/g, '$1').replace(/\[([^\]]*)\]\([^)]*\)/g, '$1');

const buildToc = readme => {
	const lines = [];
	let inCodeBlock = false;
	let inTocSection = false;

	for (const line of readme.split('\n')) {
		if (/^\s*```/.test(line)) {
			inCodeBlock = !inCodeBlock;
			continue;
		}
		if (inCodeBlock)
			continue;
		if (line.includes('AUTOGENERATED:TOC:START'))
			inTocSection = true;
		if (line.includes('AUTOGENERATED:TOC:END'))
			inTocSection = false;

		const match = line.match(/^(#{2,3}) (.+?)\s*$/);
		if (!match || inTocSection)
			continue;
		const [, hashes, rawHeading] = match;
		const heading = stripInlineMd(rawHeading);
		const indent = '\t'.repeat(hashes.length - 2);
		lines.push(`${indent}* [${heading}](#${slugify(rawHeading)})`);
	}

	return lines.join('\n');
};

const replaceMarkedSection = (readme, toc) => {
	const re = /(<!-- AUTOGENERATED:TOC:START[^\n]*-->)[\s\S]*?(<!-- AUTOGENERATED:TOC:END -->)/;
	if (!re.test(readme))
		throw new Error('Could not find "AUTOGENERATED:TOC" markers in README.md');
	return readme.replace(re, `$1\n${toc}\n$2`);
};

const readme = fs.readFileSync(readmePath, 'utf8');
fs.writeFileSync(readmePath, replaceMarkedSection(readme, buildToc(readme)));
